media:
  - name: images
    label: Images
    input: src/assets
    path: src/assets
    output: /assets
    relative: true

content:
  - name: resources
    label: Resources
    type: collection
    path: src/content/resources
    format: yaml-frontmatter
    subfolders: false
    filename: "{primary}.md"

    view:
      primary: url
      fields: [url, overrideTitle, date]
      sort: [date, url]

    fields:
      - name: url
        label: URL
        type: string
        required: true

      - name: overrideTitle
        label: Title override
        type: string
        required: false

      - name: overrideDescription
        label: Description override
        type: text
        required: false

      - name: overrideImage
        label: Image URL override
        type: string
        required: false

      - name: tags
        label: Tags
        type: string
        list: true
        required: false

      - name: date
        label: Date
        type: date
        required: false
        save_format: "YYYY-MM-DD"
