collections:
  # --- Coleção de Blog ---
  - name: Blog
    # 'name' é o rótulo que aparece na interface do CMS
    
    path: src/content/blog
    # O caminho para os arquivos .md da sua coleção
    
    can_create: true
    # Permite a criação de novos posts
    
    # 1. A integração nativa com Astro (como mostrado no vídeo)
    # Isto lê seu 'src/content/config.ts' diretamente.
    schema: astro
    
    # 2. A configuração de mídia correta (como na documentação)
    # Isto diz ao CMS como lidar com os uploads de arquivos
    # especificamente para ESTA coleção.
    media:
      # 'path': Para onde as novas imagens devem ser enviadas.
      # Para o 'z.image()' e o <Image /> do Astro,
      # DEVEMOS usar 'src/assets'.
      path: src/assets
      
      # 'return_path': O formato do caminho a ser salvo no .md
      # 'relative_from_doc' é o que precisamos.
      # Ele salvará o caminho como '../../assets/minha-imagem.jpg',
      # que é exatamente o que o 'z.image()' espera.
      return_path: relative_from_doc