# 1. Configuração de Mídia
# Define para onde o CMS deve enviar novas imagens.
# Para que a otimização de imagens do Astro (<Image />) funcione,
# elas DEVEM ser salvas dentro de 'src/assets'.
media: src/assets

collections:
  # --- Coleção de Blog ---
  - name: Blog
    # 'name' é o nome que aparecerá na interface do CMS
    
    path: src/content/blog
    # O caminho exato para seus arquivos .md
    
    can_create: true
    # Permite criar novos posts
    
    # 2. A MÁGICA DO VÍDEO
    # 'schema: astro' diz ao PagesCMS para ler seu
    # arquivo 'src/content/config.ts' automaticamente.
    #
    # Ele importará todos os campos (title, description, pubDate, heroImage)
    # e seus tipos corretos (z.string(), z.coerce.date(), image())
    # sem que você precise redefini-los aqui.
    schema: astro