public_path: public

collections:
  - name: blog
    label: Blog
    path: src/content/blog
    data_type: frontmatter
    # caminho do arquivo ao criar novo doc (usa o slug digitado no CMS)
    entry_path: "{slug}.md"
    can_create: true
    can_delete: true

    fields:
      - name: title
        label: Título
        type: text
        required: true

      - name: description
        label: Descrição Curta
        type: textarea
        required: true

      - name: pubDate
        label: Data de Publicação
        type: date
        required: true
        save_format: "YYYY-MM-DD"

      - name: heroImage
        label: Imagem de Capa
        type: image
        required: false
        # Seletor abre em src/assets e salva caminho relativo ao .md (compatível com image() do Astro)
        file_path: src/assets
        file_return_path: relative_from_doc

      - name: body
        label: Conteúdo
        type: markdown
        required: true