media:
  # Pasta padrão para gerenciar imagens (opcional, mas útil)
  - name: images
    label: Imagens
    input: src/assets
    output: /assets
    path: src/assets

content:
  - name: blog
    label: Blog
    type: collection
    path: src/content/blog
    format: yaml-frontmatter
    subfolders: false

    # Define como o nome do arquivo é gerado ao criar novo post
    # Usa o campo primário (title) + data
    filename: "{year}-{month}-{day}-{primary}.md"

    # Configurações da listagem no CMS
    view:
      primary: title
      fields: [ title, pubDate, description ]
      sort: [ pubDate, title ]

    fields:
      - name: title
        label: Título
        type: string
        required: true

      - name: description
        label: Descrição Curta
        type: text
        required: true

      - name: pubDate
        label: Data de Publicação
        type: date
        required: true
        save_format: "YYYY-MM-DD"

      - name: heroImage
        label: Imagem de Capa
        type: image
        required: false
        # Abre o seletor diretamente em src/assets
        path: src/assets

      # Conteúdo do arquivo (corpo em Markdown)
      - name: body
        label: Conteúdo
        type: text
        required: true