media:
  - name: images
    label: Imagens
    input: src/assets
    path: src/assets
    # removed: output: /assets
    relative: true

content:
  - name: blog
    label: Blog
    type: collection
    path: src/content/blog
    format: yaml-frontmatter
    subfolders: false
    filename: "{year}-{month}-{day}-{primary}.md"

    view:
      primary: title
      fields: [ title, pubDate, description ]
      sort: [ pubDate, title ]

    fields:
      - name: title
        label: Título
        type: string
        required: true

      - name: description
        label: Descrição Curta
        type: text
        required: true

      - name: pubDate
        label: Data de Publicação
        type: date
        required: true
        save_format: "YYYY-MM-DD"

      - name: heroImage
        label: Imagem de Capa
        type: image
        required: false
        path: src/assets
        relative: true
        value_template: "../../assets/{{filename}}"

      - name: body
        label: Conteúdo
        type: text
        required: true