# 1. Configuração de Pasta Pública
# Informa ao CMS onde estão seus arquivos estáticos (ex: favicon)
# No Astro, a pasta 'public' é tratada como a raiz.
public_folder: public

# 2. Configuração de Mídia Global
# Define como o CMS lida com uploads de imagens para TODAS as coleções.
media:
  # 'path': Onde as novas imagens serão salvas.
  # Para o z.image() do Astro, DEVE ser 'src/assets'.
  path: src/assets

# 3. Lista de Coleções de Conteúdo
# Este é o array que contém todas as suas seções de conteúdo.
collections:
  - name: Blog
    # 'name' é o rótulo que aparece na interface do CMS
    
    path: src/content/blog
    # O caminho para os arquivos .md da sua coleção
    
    can_create: true
    # Permite a criação de novos posts
    
    # A integração nativa com Astro (como no vídeo)
    # Isto lê 'src/content/config.ts' e gera os campos
    # (title, description, pubDate, heroImage) automaticamente.
    schema: astro